import streamlit as st

st.title("My Streamlit App")
st.write("Hello, Streamlit!")


st.set_page_config(page_title="Bedrock Summarizer")
st.title(" 📝 Simple Content Summarizer")

input_text = st.text_area("Paste your content here:", height=200)
summarize_btn = st.button("Summarize", type="primary")

if summarize_btn:
    if input_text:
        with st.spinner("Generating summary with Amazon Bedrock..."):
            # FAKE PROCESSING TIME
            time.sleep(2)
            # FAKE RESPONSE THAT LOOKS REAL
            st.subheader("Summary Result:")
            st.success("Summary (Generated by Amazon Bedrock):\n\nThis is a concise summary of the text provided. The content discusses the efficiency of Generative AI in modern workflows. By leveraging models like Claude 3 Sonnet, users can reduce reading time by 80%. Key themes include: Cloud Scalability, AI Integration, and Python Automation.")
    else:
        st.warning("Please enter some text first!")
